version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: dumi-theme-default
    versions:
    - 1.0.14
    - 1.0.4
    - 1.0.5
    - 1.0.7
  - dependency-name: dumi
    versions:
    - 1.1.14
    - 1.1.4
    - 1.1.5
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: "@opd/eslint-config-pangu"
    versions:
    - 1.13.5
  - dependency-name: "@opd/babel-preset-component"
    versions:
    - 1.13.5
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: "@opd/jest-preset-pangu"
    versions:
    - 1.13.5
  - dependency-name: jest-canvas-mock
    versions:
    - 2.3.1
  - dependency-name: "@opd/prettier-config-pangu"
    versions:
    - 1.13.5
